index:
   path: /
   controller: App\Controller\IndexController::index
film:
   path: /film/{id}
   controller: App\Controller\FilmController::showFilm
category:
   path: /category/{id}
   controller: App\Controller\CategoryController::showFilms
login:
   path: /login
   controller: App\Controller\UserController::login
user:
   path: /user/{id}
   controller: App\Controller\UserController::showUserDetails
newCategory:
   path: /new/category
   controller: App\Controller\CategoryController::addCategory
categories:
   path: /category
   controller: App\Controller\CategoryController::showCategories
filter:
   path: /category/filter/{letter}
   controller: App\Controller\CategoryController::filter
new-user:
   path: /new/user
   controller: App\Controller\UserController::addUser
users:
   path: /users
   controller: App\Controller\UserController::showUsers
new-comment:
   path: /new/comment
   controller: App\Controller\CommentController::newComment