index:
   path: /
   controller: App\Controller\IndexController::index
film:
   path: /film/{id}
   controller: App\Controller\FilmController::showFilm
category:
   path: /category/{id}
   controller: App\Controller\CategoryController::showFilms
login:
   path: /login
   controller: App\Controller\UserController::login
user:
   path: /user/{id}
   controller: App\Controller\UserController::showUserDetails
newCategory:
   path: /new/category
   controller: App\Controller\CategoryController::addCategory
